### ISSUE TITLE
Constant loading message for empty account

### ISSUE THREAD

**Issue by CharStiles** [johnozbay/Crypt-Alpha#2]
When I have zero notebooks & notes the workspace just says loading. Doesn't interfere with functionality. Very Very small ui bug :) 
Macbookpro on chrome Version 55.0.2883.95 (64-bit)

**Comment by johnozbay** [comment]
![notebook-undefined-spinning](https://cloud.githubusercontent.com/assets/611338/22709282/4ba4e92c-ed47-11e6-9ae8-2870758492a7.png)

Likely the reason is because there seems to be a mystery undefined notebook in the backend. ~ since the contents are encrypted I can't tell where / how it happened, but likely why it keeps loading.

**Comment by johnozbay** [comment]
Seems like it's because it's because **home.note** isn't being created upon account creation. 

- [ ] Create home.note in account signup

**Comment by johnozbay** [comment]
home.note is now created in signup. Both signup & library works smoothly on the test account now. no more loading message for empty accounts, closing until further notice.
